#!/bin/sh

# Extract the Jira ticket number from the commit message
ticket_number=$(git branch --show-current | grep -o 'RKS-[0-9]\+' | head -1)

# Prepend the Jira ticket number to the commit message
if [ -n "$ticket_number" ]; then
  sed -i.bak "1s/^/$ticket_number /" "$1"
fi

