name: Todos2Issues
description: Convert Todo commands to Github issues

inputs:
  left_ref:
    required: true
  right_ref:
    required: true


runs:
  using: composite
  steps:
    - shell: bash
      run: ${{ github.action_path }}/script.sh
      env:
        left_ref: ${{ inputs.left_ref }}
        right_ref: ${{ inputs.right_ref }}
