name: release

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions: write-all

jobs:
  tag-and-release:
    if: ${{ github.event.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: fetch recent tags from remote branch
        run: git checkout main && git fetch --tags origin main
      - name: Extract latest tag
        id: tag
        run: echo tag=$(git tag -l "v*" --sort=-creatordate | head -1) >> $GITHUB_OUTPUT
      - name: bump version
        id: newtag
        run: echo tag=$(echo ${{ steps.tag.outputs.tag }} | awk -F. '{print $1"."$2"."$3+1}') >> $GITHUB_OUTPUT
      - name: push tag
        run: git tag ${{ steps.newtag.outputs.tag }} && git push --tags
      - name: create release
        run: gh release create ${{ steps.newtag.outputs.tag }} --generate-notes

  release:
    if: ${{ startsWith('refs/tags', github.event.ref) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create release
        run: gh release create $(echo ${{ github.event.ref }} | cut -f 3 -d '/') --generate-notes
