name: 'Gemini AI Pull Request Review'

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  discussions: write

jobs:
  gemini-review:
    runs-on: ubuntu-latest

    steps:
      - name: Run Gemini AI Review
        uses: ablil/gemini-code-review@v0.5.10 # TODO: use latest version of a
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }} # TODO: add this secret
          github_token: ${{ secrets.GITHUB_TOKEN }}
