name: 'Publish Docker image to Github container registry'

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login ghcr.io -u USERNAME -p ${{ secrets.GITHUB_TOKEN }}

      # TODO: build your image here
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew jibDockerBuild


      # TODO: update service name
      - run: docker tag myservice:latest ghcr.io/ablil/myservice:${{ github.head_ref }} && docker push $_
        if: github.ref != 'refs/heads/main'
      - run: docker tag myservice:latest ghcr.io/ablil/myservice:latest && docker push $_
        if: github.ref == 'refs/heads/main'
