version: '3'
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - 3306:3306

  server:
    image: php:7.2-apache
    container_name: server
    volumes:
      - /var/www/html:/var/www/html
    ports:
      - 8080:80

  admin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

